import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {normalizeCard,dueCards,cleanGuess,reviewStats} from '../src/flashcard-model.js';
const headers=['id','word','phonetic','meaning','example','translation','tag','level','due','correct','attempts','imageUrl','imageFileId','updatedAt','lastReviewId'];
function fixture(){const rows=[headers];const sheet={getLastRow:()=>rows.length,getMaxRows:()=>1000,deleteRow:n=>rows.splice(n-1,1),getRange:(r,c,n,m)=>({getDisplayValues:()=>rows.slice(r-1,r-1+n).map(x=>x.slice(c-1,c-1+m).map(String)),getValues:()=>rows.slice(r-1,r-1+n).map(x=>x.slice(c-1,c-1+m)),setValues:values=>{values.forEach((v,i)=>rows[r-1+i]=v.map(x=>typeof x==='string'&&x.startsWith("'")?x.slice(1):x))}})};const ctx={SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet})},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Date};vm.createContext(ctx);vm.runInContext(fs.readFileSync('google-apps-script/Code.gs','utf8'),ctx);return {call:b=>JSON.parse(JSON.stringify(ctx.flashcards_(b))),rows};}
const card={id:'test',word:'approve',meaning:'อนุมัติ',tag:'Office'};
test('normalize and due queue handle empty and completed collections',()=>{const c=normalizeCard(card);assert.equal(c.id,'test');assert.equal(c.due,0);assert.equal(dueCards([c],1000).length,1);assert.equal(dueCards([{...c,due:2000}],1000).length,0);assert.deepEqual(reviewStats([]),{attempts:0,accuracy:0,mastered:0});assert.equal(cleanGuess(' APPROVE '),'approve');});
test('review is idempotent and editing preserves progress',()=>{const f=fixture();f.call({action:'cards_upsert',card});const r=f.call({action:'cards_review',id:'test',remembered:true,reviewId:'r1'});assert.equal(r.card.level,1);assert.equal(r.card.attempts,1);assert(r.card.due>Date.now());assert.equal(f.call({action:'cards_review',id:'test',remembered:true,reviewId:'r1'}).card.attempts,1);assert.equal(f.call({action:'cards_upsert',card:{...card,meaning:'ยอมรับ'}}).card.attempts,1);const retry=f.call({action:'cards_review',id:'test',remembered:false,reviewId:'r2'}).card;assert.equal(retry.level,0);assert.equal(retry.attempts,2);assert.equal(retry.correct,1);});
test('import skips existing IDs and validates before writes',()=>{const f=fixture();f.call({action:'cards_upsert',card});f.call({action:'cards_import',cards:[{...card,meaning:'old data'}, {...card,id:'two'}]});assert.equal(f.rows.length,3);assert.equal(f.call({action:'cards_list'}).cards[0].meaning,card.meaning);assert.throws(()=>f.call({action:'cards_import',cards:[{...card,id:'three'},{id:'bad'}]}));assert.equal(f.rows.length,3);});
test('unsafe image schemes and invalid statistics are rejected',()=>{const f=fixture();assert.throws(()=>f.call({action:'cards_upsert',card:{...card,imageUrl:'javascript:alert(1)'}}));assert.throws(()=>f.call({action:'cards_import',cards:[{...card,attempts:0,correct:2}]}));});
