import React, {useState} from 'react';
export const localDay = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let audio;
export function unlockSound(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function tone(freq,start,duration,type,volume){if(!audio||audio.state!=='running')return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.005);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain);gain.connect(audio.destination);osc.start(start);osc.stop(start+duration+.01);osc.onended=()=>{osc.disconnect();gain.disconnect()};}
export function woodStep(){if(!audio||audio.state!=='running')return;const t=audio.currentTime; tone(150+Math.random()*35,t,.08,'triangle',.09);tone(480+Math.random()*70,t,.035,'sine',.035);const buffer=audio.createBuffer(1,Math.ceil(audio.sampleRate*.035),audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/(data.length*.16));const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=buffer;filter.type='bandpass';filter.frequency.value=1100;gain.gain.value=.12;source.connect(filter);filter.connect(gain);gain.connect(audio.destination);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect()};}
export function winSound(){if(!audio||audio.state!=='running')return;[523.25,659.25,783.99,1046.5,1318.5].forEach((f,i)=>tone(f,audio.currentTime+i*.105,i===4?.4:.14,'square',.055));}
export function youtubeId(value){try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol))return null;const host=u.hostname.toLowerCase();let id;if(host==='youtu.be')id=u.pathname.split('/')[1];else if(['youtube.com','www.youtube.com','m.youtube.com','music.youtube.com'].includes(host))id=u.pathname==='/watch'?u.searchParams.get('v'):['embed','shorts','live'].includes(u.pathname.split('/')[1])?u.pathname.split('/')[2]:null;return /^[\w-]{11}$/.test(id||'')?id:null;}catch{return null}}
export function MusicPlayer(){const [saved,setSaved]=useState(()=>read('grow-youtube',''));const [url,setUrl]=useState(saved);const [open,setOpen]=useState(false);const [error,setError]=useState('');const id=youtubeId(saved);return <div className="musicWidget"><button type="button" className="musicToggle" onClick={()=>setOpen(!open)} aria-expanded={open}>♫ เพลงโฟกัส</button>{open&&<div className="musicPanel"><button type="button" className="musicClose" onClick={()=>setOpen(false)} aria-label="ปิดเพลง">ปิด ×</button><h3>เพลงระหว่างโฟกัส</h3><form onSubmit={e=>{e.preventDefault();if(!youtubeId(url)){setError('ใส่ลิงก์วิดีโอ YouTube ที่ถูกต้อง');return}try{localStorage.setItem('grow-youtube',JSON.stringify(url));setSaved(url);setError('')}catch{setError('จำลิงก์ไม่ได้ พื้นที่เก็บข้อมูลอาจเต็ม')}}}><label htmlFor="music-url">ลิงก์ YouTube</label><div className="musicInput"><input id="music-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=…" required/><button>ใช้เพลงนี้</button></div></form>{error&&<p role="alert">{error}</p>}{id&&<><iframe key={id} title="เพลงโฟกัสจาก YouTube" src={`https://www.youtube.com/embed/${id}`} allow="encrypted-media; picture-in-picture; fullscreen" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/><a href={`https://www.youtube.com/watch?v=${id}`} target="_blank" rel="noopener noreferrer">เปิดใน YouTube หากเพลงนี้เล่นในเว็บไม่ได้ ↗</a><button onClick={()=>{try{localStorage.removeItem('grow-youtube');setSaved('');setUrl('')}catch{setError('ลบลิงก์ไม่สำเร็จ')}}}>ล้างเพลง</button></>}<small>กดเล่นในวิดีโอ · ปิดช่องนี้เพื่อหยุดเพลง</small></div>}</div>}
export {SmallWins} from './wins';
